export const UNAUTHENTICATED = {
  message: "Unauthorized",
  code: 401,
};

export const sourceOptions = [
  "New York Times",
  "Washington Post",
  "BBC News",
  "CNN",
  "Fox News",
  "Business Insider",
  "The Verge",
  "ESPN",
  "Gizmodo.com",
  "Slashdot.org",
  "Yahoo Entertainment",
];
export const categoryOptions = [
  "Graphics",
  "RealEstate",
  "Books",
  "Letters",
  "Foreign",
  "The Verge",
  "BBC News",
  "Business Insider",
  "Yahoo Entertainment",
  "ESPN",
  "Television & radio",
  "UK news",
  "Society",
  "Film",
  "From the Guardian",
  "Opinion",
  "Fashion",
  "Life and style",
  "Books",
  "Travel",
  "Music",
];
export const authorOptions = [
  "By Debra Kamin",
  "By J. D. Biersdorfer",
  "By Isayen Herrera, Julie Turkewitz, Genevieve Glatsky and Adriana Loureiro Fernandez",
  "By Nader Ibrahim and Daniel Berehulak",
  "Jay Peters",
  "Jordan Raanan",
  "Liam McLeod",
  "Hannah Abraham",
  "Sean Kearns",
  "EditorDavid",
  "Lucas Ropek",
  "AMY TAXIN Associated Press",
  "David Newton",
  "HANNA ARHIROVA and SAMYA KULLAB",
  "Bruce Schneier",
  "Todd Feathers",
  "Dua Rashid",
  "Rob Schmitz",
  "techkritiko@gmail.com (Jay Bonggolto)",
  "Reuters",
  "Hanna Arhirova and Samya Kullab, Associated Press",
  "Laura Dobberstein",
  "Brittney Melton",
  "Erin Liam",
  "kcloonan@insider.com (Kelly Cloonan)",
  "Jason Kottke",
  "harish.jonnalagadda@futurenet.com (Harish Jonnalagadda)",
];
